config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  get 'luthiers' => 'pages#luthiers'
  get 'contacto' => 'pages#contacto'
  get 'about' => 'pages#about'

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


   validate :has_at

   def has_at
   	unless email.include?("@")
   		errors.add(:email, "must contain @")
   	end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


	def luthiers
	end

	def contacto
	end

	def about
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
	end
	def show
		@post = Post.find(params[:id])
	end	
	def new
	end
	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params)
		@post.save
		redirect_to @post
	end

	private def post_params

		params.require(:post).permit(:title, :body)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portafolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>



  
  <body>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   <header class="cover"><nav>
      <a href='/'>Home</a>
      <a href='/about'>Musica</a>
      <a href='/luthiers'>Luthier</a>
      <a href='/contacto'>Localizacion</a>
      <a href='/posts/new'>Escribanos</a>
      
    </nav>
  </br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <div id='hola'> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></div> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
   </header>


    
     
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<header></header>


<div class="container">

  <div class="row">
  	
  	<div class="col"><h1>Sebastian Rios</h1>
	Soy apasionado por la percusion y trabajo en orquestas de salsa, musica clasica y rock. 
	Estoy viviendo en Argentina rodeado de un ambiente totalmente musical. Empece a trabajar como luthier 
	desde hace unos anios debido a que tambien me gusta la carpinteria por que vengo de una familia de 
	tradicion de ebanistas y artistas.
	</div>
	<div class="col"> <%= image_tag("maraquero.jpg") %></div>

  </div>

</div>

app/views/pages/contacto.html.erb
<h1>Salcedo 4218</h1>
<h3>Boedo</h3>
<h4>Buenos Aires, <b>Argentina</b></h4>

<div id="title">Localizacion</div>
<div id="map"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC46oCtaJBhjqqC_3i-VDbWQZsAAXIC7vU&callback=initMap" async defer></script>

app/views/pages/luthiers.html.erb
<div class="container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="<%= asset_path("pianista.jpg") %>" alt="Universidad" style="width:50%;">
      </div>

      <div class="item">
        <img src="<%= asset_path("afiche.jpg") %>" alt="Orquesta de Salsa" style="width:50%;">
      </div>
    
      <div class="item">
        <img src="<%= asset_path("maraquero.jpg") %>" alt="Batuta" style="width:50%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/posts/index.html.erb
<header class="cover"></header>

<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/dd64ocL1M2E" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</body>
<footer>


<nav>
     <a href="https://www.instagram.com/sebastianriosdr/"><%= image_tag("instagram.png") %></a>
     <a href="https://www.facebook.com/drumandsebass"><%= image_tag("facebook.png") %></a>
     <a href="https://www.facebook.com/drumandsebass"><%= image_tag("twitter.png") %></a>
      
    </nav>

</footer>

app/views/posts/new.html.erb
<h1>Este espacio es para un comentario</h1> 

<%= form_for :post, url: posts_path  do |f| %>

	<p>
		<%= f.label :titulo %> <br>
		<%= f.text_field :title %>
	</p>


 <p> 
 	<%= f.label :Comentario %> <br>
 	<%= f.text_area :body %>
 </p>


 <p>
 	<%= f.submit %>
 </p>

 <% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>